// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/test.proto

package test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Contact struct {
	Firstname            string   `protobuf:"bytes,1,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,2,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc70169f84046e97, []int{0}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Contact) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type HelloMsg struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloMsg) Reset()         { *m = HelloMsg{} }
func (m *HelloMsg) String() string { return proto.CompactTextString(m) }
func (*HelloMsg) ProtoMessage()    {}
func (*HelloMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc70169f84046e97, []int{1}
}

func (m *HelloMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloMsg.Unmarshal(m, b)
}
func (m *HelloMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloMsg.Marshal(b, m, deterministic)
}
func (m *HelloMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloMsg.Merge(m, src)
}
func (m *HelloMsg) XXX_Size() int {
	return xxx_messageInfo_HelloMsg.Size(m)
}
func (m *HelloMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloMsg.DiscardUnknown(m)
}

var xxx_messageInfo_HelloMsg proto.InternalMessageInfo

func (m *HelloMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Contact)(nil), "test.Contact")
	proto.RegisterType((*HelloMsg)(nil), "test.HelloMsg")
}

func init() { proto.RegisterFile("proto/test.proto", fileDescriptor_fc70169f84046e97) }

var fileDescriptor_fc70169f84046e97 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x03, 0x33, 0x85, 0x58, 0x40, 0x6c, 0x25, 0x67, 0x2e,
	0x76, 0xe7, 0xfc, 0xbc, 0x92, 0xc4, 0xe4, 0x12, 0x21, 0x19, 0x2e, 0x4e, 0xb7, 0xcc, 0xa2, 0xe2,
	0x92, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x84, 0x80, 0x90, 0x14,
	0x17, 0x87, 0x4f, 0x22, 0x54, 0x92, 0x09, 0x2c, 0x09, 0xe7, 0x2b, 0xc9, 0x70, 0x71, 0x78, 0xa4,
	0xe6, 0xe4, 0xe4, 0xfb, 0x16, 0xa7, 0x0b, 0x09, 0x70, 0x31, 0xfb, 0x16, 0xa7, 0x43, 0xf5, 0x83,
	0x98, 0x46, 0x46, 0x5c, 0xac, 0x60, 0x59, 0x21, 0x4d, 0x2e, 0x8e, 0xe0, 0xc4, 0x4a, 0x08, 0x9b,
	0x57, 0x0f, 0xec, 0x14, 0xa8, 0xdd, 0x52, 0x7c, 0x10, 0x2e, 0xcc, 0x14, 0x27, 0x9e, 0x28, 0x2e,
	0x84, 0x83, 0x93, 0xd8, 0xc0, 0x6c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x4a, 0x96,
	0xeb, 0xc5, 0x00, 0x00, 0x00,
}
