// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/OES.proto

package OES

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Lesson struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lesson) Reset()         { *m = Lesson{} }
func (m *Lesson) String() string { return proto.CompactTextString(m) }
func (*Lesson) ProtoMessage()    {}
func (*Lesson) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2cf09a92270579e, []int{0}
}

func (m *Lesson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lesson.Unmarshal(m, b)
}
func (m *Lesson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lesson.Marshal(b, m, deterministic)
}
func (m *Lesson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lesson.Merge(m, src)
}
func (m *Lesson) XXX_Size() int {
	return xxx_messageInfo_Lesson.Size(m)
}
func (m *Lesson) XXX_DiscardUnknown() {
	xxx_messageInfo_Lesson.DiscardUnknown(m)
}

var xxx_messageInfo_Lesson proto.InternalMessageInfo

type UserToken struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserToken) Reset()         { *m = UserToken{} }
func (m *UserToken) String() string { return proto.CompactTextString(m) }
func (*UserToken) ProtoMessage()    {}
func (*UserToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2cf09a92270579e, []int{1}
}

func (m *UserToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserToken.Unmarshal(m, b)
}
func (m *UserToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserToken.Marshal(b, m, deterministic)
}
func (m *UserToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToken.Merge(m, src)
}
func (m *UserToken) XXX_Size() int {
	return xxx_messageInfo_UserToken.Size(m)
}
func (m *UserToken) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToken.DiscardUnknown(m)
}

var xxx_messageInfo_UserToken proto.InternalMessageInfo

type State struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2cf09a92270579e, []int{2}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

type UserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2cf09a92270579e, []int{3}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

type UserMsg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMsg) Reset()         { *m = UserMsg{} }
func (m *UserMsg) String() string { return proto.CompactTextString(m) }
func (*UserMsg) ProtoMessage()    {}
func (*UserMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2cf09a92270579e, []int{4}
}

func (m *UserMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMsg.Unmarshal(m, b)
}
func (m *UserMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMsg.Marshal(b, m, deterministic)
}
func (m *UserMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMsg.Merge(m, src)
}
func (m *UserMsg) XXX_Size() int {
	return xxx_messageInfo_UserMsg.Size(m)
}
func (m *UserMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UserMsg proto.InternalMessageInfo

type LessonResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LessonResponse) Reset()         { *m = LessonResponse{} }
func (m *LessonResponse) String() string { return proto.CompactTextString(m) }
func (*LessonResponse) ProtoMessage()    {}
func (*LessonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2cf09a92270579e, []int{5}
}

func (m *LessonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LessonResponse.Unmarshal(m, b)
}
func (m *LessonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LessonResponse.Marshal(b, m, deterministic)
}
func (m *LessonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LessonResponse.Merge(m, src)
}
func (m *LessonResponse) XXX_Size() int {
	return xxx_messageInfo_LessonResponse.Size(m)
}
func (m *LessonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LessonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LessonResponse proto.InternalMessageInfo

type AssignmentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignmentResponse) Reset()         { *m = AssignmentResponse{} }
func (m *AssignmentResponse) String() string { return proto.CompactTextString(m) }
func (*AssignmentResponse) ProtoMessage()    {}
func (*AssignmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2cf09a92270579e, []int{6}
}

func (m *AssignmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignmentResponse.Unmarshal(m, b)
}
func (m *AssignmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignmentResponse.Marshal(b, m, deterministic)
}
func (m *AssignmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignmentResponse.Merge(m, src)
}
func (m *AssignmentResponse) XXX_Size() int {
	return xxx_messageInfo_AssignmentResponse.Size(m)
}
func (m *AssignmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AssignmentResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Lesson)(nil), "OES.Lesson")
	proto.RegisterType((*UserToken)(nil), "OES.UserToken")
	proto.RegisterType((*State)(nil), "OES.State")
	proto.RegisterType((*UserResponse)(nil), "OES.UserResponse")
	proto.RegisterType((*UserMsg)(nil), "OES.UserMsg")
	proto.RegisterType((*LessonResponse)(nil), "OES.LessonResponse")
	proto.RegisterType((*AssignmentResponse)(nil), "OES.AssignmentResponse")
}

func init() { proto.RegisterFile("proto/OES.proto", fileDescriptor_a2cf09a92270579e) }

var fileDescriptor_a2cf09a92270579e = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0x31, 0x0b, 0xc2, 0x30,
	0x10, 0x85, 0x07, 0xb5, 0x31, 0xaf, 0x52, 0xb5, 0x38, 0x39, 0xde, 0x2c, 0x15, 0xd4, 0x3f, 0xa0,
	0xd0, 0x4d, 0x29, 0x58, 0x5d, 0xdc, 0x14, 0x8e, 0x20, 0x62, 0x52, 0x7a, 0xf9, 0xff, 0x48, 0x52,
	0xcc, 0xf6, 0xbd, 0x17, 0xbe, 0xdc, 0xc3, 0xbc, 0xeb, 0x9d, 0x77, 0xdb, 0xa6, 0x6e, 0xab, 0x48,
	0xe5, 0xa8, 0xa9, 0x5b, 0x9a, 0x22, 0x3b, 0xb3, 0x88, 0xb3, 0x94, 0x43, 0xdf, 0x85, 0xfb, 0x9b,
	0xfb, 0xb0, 0x25, 0x85, 0x49, 0xeb, 0x9f, 0x9e, 0xa9, 0xc0, 0x2c, 0xb4, 0x57, 0x96, 0xce, 0x59,
	0x61, 0xd2, 0x50, 0x21, 0x5f, 0xc4, 0xd0, 0x02, 0xc5, 0xa0, 0xa6, 0xc7, 0x15, 0xca, 0xa3, 0xc8,
	0xdb, 0xd8, 0x2f, 0x5b, 0xff, 0x6f, 0x77, 0x07, 0x8c, 0x83, 0x52, 0x6e, 0xa0, 0x0c, 0xfb, 0x88,
	0x45, 0x15, 0x66, 0xa4, 0x73, 0xeb, 0x65, 0xca, 0xc9, 0xd2, 0x50, 0xc3, 0xef, 0x72, 0xca, 0x1f,
	0x3a, 0x6d, 0x7f, 0x65, 0x11, 0xf7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x83, 0x3a, 0x30,
	0xcf, 0x00, 0x00, 0x00,
}
